// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehmoavsaewmocixnkjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobW9hdnNhZXdtb2NpeG5ranNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDA2NjksImV4cCI6MjA3MzAxNjY2OX0.0GumBGSYdIO2sUhYaaFDgFMv2s1L-4mJmNlXBYC_Gxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});